spring:
  application:
    name: module-infrastructure

  datasource:
    url: jdbc:mysql://localhost:3306/helmnelm
    username: helmnelm
    password: helmnelm123

  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.MySQL8Dialect
